//Tracing projectiles goes here

CLASS Tracer2: FastProjectile
{
DEFAULT
{
missiletype "TracerTrailMain";
missileheight 7;
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
	// +BLOODSPLATTER ;
	+NOEXTREMEDEATH;
	damage 0;
	radius 2;
	height 2;
	speed 140;
	renderstyle "ADD";
	alpha 0.9;
	scale .15;
	//Damagetype "Weak"
}
		states
			{
		Spawn:
			TRAC A 1 BRIGHT;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 1;
			//TNT1 A 0 A_JumpIfInTargetInventory("IsTacticalClass", 1, "Tactical")
			tnt1 a 2;
			Stop;
			
		XDeath:
			TNT1 A 0;
			Stop;
		
		Tactical:
			TNT1 A 0;
			TNT1 A 0 A_Explode(8, 50);
			Stop;
			}
}

CLASS TracerTrailMain2: Actor
{
DEFAULT
{
Scale 0.03;
alpha 0.8;
+NOGRAVITY;
+NOCLIP;
+DontSplash;
RenderStyle "Add";
}
States
{
Spawn:
PART A 1 Bright A_FadeOut(0.4, 1);
loop;
}
}