// Just In Case.
class ArachnotronS : SS_ScriptedSpawner replaces Arachnotron
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        //if(GetCvar("bd_classicmonsters")){return 'TehLostSoul';} 
		if(GetCvar("bd_disablenewenemies")){return 'Arachnotron1';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'Arachnotron1';
    }
}

/*
Class ArachnotronS : Actor Replaces Arachnotron
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
	SpawnArachnotron:
	    TNT1 A 0 A_SpawnItemEx("Arachnotron1",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/