class ArchVileS : SS_ScriptedSpawner replaces Archvile
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        if(GetCvar("bd_classicmonsters")){return 'VanillaArchvile';} 
		if(GetCvar("bd_disablenewenemies")){return 'TehArchvile';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'TehArchvile';
    }
}

/*
Class ArchVileS : Actor Replaces Archvile
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
		TNT1 A 0
		{
		If(GetCvar("bd_classicmonsters")==1)   { return resolvestate("ReplaceVanilla");}
		return resolvestate("SpawnArchVile"); 
		}
	ReplaceVanilla:
	    TNT1 A 0 A_SpawnItemEx("VanillaArchvile",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;	
	SpawnArchVile:
	    TNT1 A 0 A_SpawnItemEx("TehArchvile",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/