class BaronS : SS_ScriptedSpawner replaces BaronofHell
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        if(GetCvar("bd_classicmonsters")){return 'VanillaBaronOfHell';} 
		if(GetCvar("bd_disablenewenemies")){return 'BaronofHell2';}
		if(X == 304){return 'BaronBoss1';}
		if(X == 528){return 'BaronBoss2';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'BaronofHell2';
    }
}

/*
Class BaronS : Actor Replaces BaronofHell
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
		TNT1 A 0
		{
		If(GetCvar("bd_classicmonsters")==1)   { return resolvestate("ReplaceVanilla");}
		return resolvestate("SpawnBaron"); 
		}	
	ReplaceVanilla:
	    TNT1 A 0 A_SpawnItemEx("VanillaBaronOfHell",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;
	SpawnBaron:
	    TNT1 A 0 A_SpawnItemEx("BaronofHell2",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/