class CacodemonS : SS_ScriptedSpawner replaces Cacodemon
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        if(GetCvar("bd_classicmonsters")){return 'VanillaCacoDemon';} 
		if(GetCvar("bd_disablenewenemies")){return 'Cacodemon_';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'Cacodemon_';
    }
}

/*
Class CacodemonS : Actor Replaces Cacodemon
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
		TNT1 A 0
		{
		If(GetCvar("bd_classicmonsters")==1)   { return resolvestate("ReplaceVanilla");}
		return resolvestate("SpawnCD"); 
		}
	ReplaceVanilla:
	    TNT1 A 0 A_SpawnItemEx("VanillaCacoDemon",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;
	SpawnCD:
	    TNT1 A 0 A_SpawnItemEx("Cacodemon_",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/