class ChaingunGuyS : SS_ScriptedSpawner replaces ChaingunGuy
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        if(GetCvar("bd_classicmonsters")){return 'VanillaChaingunguy';} 
		if(GetCvar("bd_disablenewenemies")){return 'ChaingunGuy1';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'ChaingunGuy1';
    }
} 

/*
Class ChaingunGuyS : Actor Replaces ChaingunGuy
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
		TNT1 A 0
		{
		If(GetCvar("bd_classicmonsters")==1)   { return resolvestate("ReplaceVanilla");}
		return resolvestate("SpawnCommando"); 
		}	
	ReplaceVanilla:
	    TNT1 A 0 A_SpawnItemEx("VanillaChaingunguy",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;
	SpawnCommando:
	    TNT1 A 0 A_SpawnItemEx("ChaingunGuy1",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}

*/