class CyberdemonS : SS_ScriptedSpawner replaces Cyberdemon
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        if(GetCvar("bd_classicmonsters")){return 'VanillaCyberdemon';} 
		if(GetCvar("bd_disablenewenemies")){return 'TheCyberdemon';}
		if(X == -1472){return 'CyberdemonBoss';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'TheCyberdemon';
    }
}

/*
Class CyberdemonS : Actor Replaces Cyberdemon
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
		TNT1 A 0
		{
		If(GetCvar("bd_classicmonsters")==1)   { return resolvestate("ReplaceVanilla");}
		return resolvestate("SpawnCD"); 
		}
	ReplaceVanilla:
	    TNT1 A 0 A_SpawnItemEx("VanillaCyberdemon",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;
	SpawnCD:
	    TNT1 A 0 A_SpawnItemEx("TheCyberdemon",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/