// Just In Case.
class LostSoulS : SS_ScriptedSpawner replaces LostSoul
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        //if(GetCvar("bd_classicmonsters")){return 'TehLostSoul';} 
		if(GetCvar("bd_disablenewenemies")){return 'TehLostSoul';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'TehLostSoul';
    }
}

/*
Class LostSoulS : Actor Replaces LostSoul
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
	SpawnLostSoul:
	    TNT1 A 0 A_SpawnItemEx("TehLostSoul",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/
