class MasterMindS : SS_ScriptedSpawner replaces SpiderMastermind
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        if(GetCvar("bd_classicmonsters")){return 'VanillaSpiderMastermind';} 
		if(GetCvar("bd_disablenewenemies")){return 'TheSpiderMastermind';}
		// Shit Necessary so maps don't Break.
		if(X == 1600){return 'SuperMastermind';}
		if(X == -2720){return 'MotherDemon';}
		if(X == 0){return 'MotherDemon';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'TheSpiderMastermind';
    }
}

/*
Class MasterMindS : Actor Replaces SpiderMastermind
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
		TNT1 A 0
		{
		If(GetCvar("bd_classicmonsters")==1)   { return resolvestate("ReplaceVanilla");}
		return resolvestate("SpawnMM"); 
		}
	ReplaceVanilla:
	    TNT1 A 0 A_SpawnItemEx("VanillaSpiderMastermind",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;	
	SpawnMM:
	    TNT1 A 0 A_SpawnItemEx("TheSpiderMastermind",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/