class RevenantS : SS_ScriptedSpawner replaces Revenant
{
    override name SS_GetActorToSpawn ()
    {
	    // Assuming '' is a boolean console variable.
                                      // And '' is true.
        if(GetCvar("bd_classicmonsters")){return 'VanillaRevenant';} 
		if(GetCvar("bd_disablenewenemies")){return 'Revenant1';}
		// Not Really Needed Here, but you never know, i might add more.
		// '' is false, Spawn Other Enemies.

        return 'Revenant1';
    }
}

/*
Class RevenantS : Actor Replaces Revenant
{
		Default
	{
		+NOINTERACTION
	}
	
	States
	{
	Spawn:
	    TNT1 A 0; 
		TNT1 A 0
		{
		If(GetCvar("bd_classicmonsters")==1)   { return resolvestate("ReplaceVanilla");}
		return resolvestate("SpawnR"); 
		}	
	ReplaceVanilla:
	    TNT1 A 0 A_SpawnItemEx("VanillaRevenant",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;
	SpawnR:
	    TNT1 A 0 A_SpawnItemEx("Revenant1",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
	    Stop;		
	}
}
*/