CLASS BIG_FUCKING_GUN : BrutalWeapon
{
 bool Inspected;
 int BFGCharge;
 DEFAULT
 {
    //Game Doom
	Height 20;
	//SpawnID 31;
	Weapon.SelectionOrder 101;
	Weapon.AmmoUse 0;
	Weapon.AmmoGive 0;
	Weapon.AmmoType1 "BFGAmmo";
	//Weapon.AmmoType2 "BFGBattery";
	//Weapon.AmmoType2 "BFGAmmo";
    Inventory.PickupSound "BFGREADY";
	//DamageType Desintegrate
	+FORCEXYBILLBOARD;
	+WEAPON.NOAUTOFIRE;
	Tag "BFG 9000";
    Inventory.PickupMessage "You got the BFG-9000! FUCK YEAH!";
	Inventory.Icon "BFUGA0";
}
	States
	{
	
	Ready3:
	Ready:
		BFGN ABCDEFGHIJ 1
		{
		 A_WeaponReady();
		 If(CountInv("Kicking") >=1 ) {return resolvestate("DoKick");}
		 Else If(CountInv("Taunting") >=1 ) {return resolvestate("Taunt");}
		 Else If(CountInv("Salute1") >=1 ) {return resolvestate("Salute");}
		 Else If(CountInv("TossGrenade") >=1 ) {return resolvestate("TossGrenade");}
		 Else If(CountInv("QuickMelee") >=1 ) {return resolvestate("DoQuickMelee");}
		 else{return resolvestate(null);}
		}
		Loop;

	NoAmmo:
		BFGN A 1;
		BFGN A 0 A_PlaySound("weapons/empty", 4);
		Goto Ready;
	/*	
	NoAmmo2:
		BFGN A 0 A_JumpIfInventory("Kicking",1,"DoKick");
        BFGN A 0 A_JumpIfInventory("Taunting",1,"Taunt");
		BFGN A 0 A_JumpIfInventory("Salute1", 1, "Salute");
		BFGN A 0 A_JumpIfInventory("Salute2", 1, "Salute");
		BFGN A 0 A_JumpIfInventory("TossGrenade",1,"TossGrenade");
		BFGN A 0 A_JumpIfInventory("IsRunning",1,"CheckSprint");
		BFGN A 0 A_JumpIfInventory("ExecuteDownedEnemy", 1, "DoExecution");
		BFGN A 0 A_JumpIfInventory("QuickMelee",1,"DoQuickMelee");
		//TNT1 A 0 A_JumpIfInventory("TurboReload",1,"TurboReload");
		//TNT1 A 0 A_JumpIfInventory("NoAutoReload", 1, "NoAmmo2");
		//SHTZ A 0 A_JumpIfInventory("BFGAmmo",1,"Reload");
		Goto NoAmmo;
	*/	
	/*	
	
	CheckSprint:
		BFGN A 1 A_WeaponReady(WRF_NOFIRE);
		BFGN A 0 A_JumpIfInventory("IsStandingStill", 1, "Ready3");
		BFGN A 0 A_JumpIfInventory("IsTacticalClass", 1, "StartSprint");
		Goto Ready;
		
	StartSprint:
		BFGN A 1 A_WeaponReady(WRF_NOFIRE);
		BFGN A 0 A_Takeinventory("Zoomed",1);
		BFGN A 0 A_Takeinventory("ADSmode",1);
		BFGN A 0 A_ZoomFactor(1.0);
		BFGN A 0 A_JumpIfInventory("UsedStamina", 40, "StopSprintTired");
		
	Sprinting:	
		BFSP A 0 offset(-9,32) 
		BFGN A 0 offset(-9,32) A_JumpIfInventory("IsStandingStill", 1, "Ready3")
		BFGN A 0 offset(-9,32) A_JumpIfInventory("UsedStamina", 100, "StopSprintTired")
		PLAY A 0 offset(-9,32) ACS_ExecuteAlways(852, 0, 0, 0, 0)//Makes player faster.
		BFGN A 0 offset(-9,32) A_JumpIfInventory("PowerStrength", 1, 2)
		BFGN A 0 offset(-9,32) A_GiveInventory("UsedStamina", 13)
		BFGN A 0 offset(-9,32)
		BFSP A 1 offset(-9,34) A_SetPitch(pitch -0.5)
		BFSP A 1 offset(-6,36) A_SetPitch(pitch -0.5)
		BFSP A 1 offset(-3,38) A_SetPitch(pitch -0.5)
		BFSP A 1 offset(0,38) A_SetPitch(pitch -0.5)
		BFSP A 1 offset(3,36) A_SetPitch(pitch -0.5)
		BFSP A 1 offset(6,34) A_SetPitch(pitch -0.5)
		BFSP A 1 offset(9,32) A_SetPitch(pitch -0.5)
		BFGN A 0 offset(9,32) A_WeaponReady(WRF_NOBOB)
		BFGN A 0 A_JumpIfInventory("Kicking",1,"DoKick")
        BFGN A 0 A_JumpIfInventory("Taunting",1,"Taunt")
        BFGN A 0 A_JumpIfInventory("Reloading",1,"Reload")
		BFGN A 0 offset(-9,32) A_GiveInventory("UsedStamina", 13)
		BFGN A 0 offset(9,33) A_SpawnItemEx("FootStep", 0, 0, 2, 0, 0, -4)
		BFSP A 1 offset(9,34) A_SetPitch(pitch +0.5)
		BFSP A 1 offset(6,36) A_SetPitch(pitch +0.5)
		BFSP A 1 offset(3,38) A_SetPitch(pitch +0.5)
		BFSP A 1 offset(0,38) A_SetPitch(pitch +0.5)
		BFSP A 1 offset(-3,36) A_SetPitch(pitch +0.5)
		BFSP A 1 offset(-6,34) A_SetPitch(pitch +0.5)
		BFSP A 1 offset(-9,32) A_SetPitch(pitch +0.5)
		BFGN A 0 offset(-9,32) A_WeaponReady(WRF_NOBOB)
		BFGN A 0 offset(-9,32) A_JumpIfInventory("IsRunning", 1, "Sprinting")
		Goto StopSprint
		
	StopSprintTired:
		BFGN A 1
		PLAY A 0 ACS_ExecuteAlways(853, 0, 0, 0, 0)//Makes player slower.
		BFGN A 0 A_PlaySound("Tired", 2)
		BFGN A 0 A_TakeInventory("UsedStamina", 2)
		BFGN A 5 A_WeaponReady
		BFGN A 0 A_TakeInventory("UsedStamina", 2)
		BFGN A 5 A_WeaponReady
		BFGN A 0 A_TakeInventory("UsedStamina", 2)
		BFGN A 5 A_WeaponReady
		BFGN A 0 A_TakeInventory("UsedStamina", 2)
		BFGN A 5 A_WeaponReady
		BFGN A 0 A_TakeInventory("UsedStamina", 2)
		BFGN A 5 A_WeaponReady
		Goto Ready
	StopSprint:
		BFSP A 1
		BFGN A 0 A_JumpIfInventory("UsedStamina", 60, "StopSprintTired")
		PLAY A 0 ACS_ExecuteAlways(853, 0, 0, 0, 0)//Makes player slower.
		Goto Ready
	*/	
		
	Deselect:
	    TNT1 A 0
		{
		A_Giveinventory("ScreenTilt",1);
		A_Setroll(0, SPF_INTERPOLATE);
	    A_Takeinventory("ScreenTilt",1);
	    }
	   // TNT1 AAAAAAAAAAAAAAAAAA 0 A_Lower
		BFGN A 0 A_TakeInventory("TossGrenade", 1);
		BFGS DCBA 1; //A_Lower
		TNT1 A 0 ZWL_QuickLower();
		Wait;
		
	Select:
		TNT1 A 0
		{
		A_Giveinventory("ScreenTilt",1);
		A_Setroll(0, SPF_INTERPOLATE);
	    A_Takeinventory("ScreenTilt",1);
	    }
		BFGN A 0 A_Giveinventory("GoSpecial",1);
		BFGN A 0 A_Takeinventory("FistsSelected",1);
		BFGN A 0 A_Takeinventory("SawSelected",1);
		RIFG A 0 A_Takeinventory("RifleSelected",1);
		BFGN A 0 A_Takeinventory("ShotgunSelected",1);
		BFGN A 0 A_Takeinventory("SSGSelected",1);
		BFGN A 0 A_Takeinventory("MinigunSelected",1);
		BFGN A 0 A_Takeinventory("PlasmaGunSelected",1);
		BFGN A 0 A_Takeinventory("RocketLauncherSelected",1);
		BFGN A 0 A_Takeinventory("GrenadeLauncherSelected",1);
		BFGN A 0 A_Giveinventory("BFGSelected",1);
		BFGN A 0 A_Takeinventory("BFG10kSelected",1);
		BFGN A 0 A_Takeinventory("RailGunSelected",1);
		BFGN A 0 A_Takeinventory("SubMachineGunSelected",1);
		BFGN A 0 A_Takeinventory("RevenantLauncherSelected",1);
		BFGN A 0 A_Takeinventory("LostSoulSelected",1);
		BFGN A 0 A_Takeinventory("FlameCannonSelected",1);
		BFGN A 0 A_Takeinventory("HasBarrel",1);
		BFGN A 0 A_TakeInventory("TossGrenade", 1);
		BFGN A 0 A_JumpIfInventory("GoFatality", 1, "Steady");
        BFGN A 0 A_PlaySound("BFGREADY");
		TNT1 A 0 ZWL_QuickRaise();
		SelectAnimation:
		BFGS ABCD 1;
		Goto Ready;

		
	Fire:
		BFGN A 0;
		SHTZ A 0 A_JumpIfInventory("BFGAmmo",1,1);
		Goto NoAmmo;
        BFGN A 0 A_PlaySound("BFGCHARGE",1);
		//BFGN A 0 A_PlaySound("BFGFIRE")
		BFGC ABCDEFGHI 1 BRIGHT A_FireCustomMissile("GreenFlareSpawn",0,0,0,0);
		BFGC ABCDEFGHI 1 BRIGHT A_FireCustomMissile("GreenFlareSpawn",0,0,0,0);
		BFGC ABCDEFGHI 1 BRIGHT A_FireCustomMissile("GreenFlareSpawn",0,0,0,0);
		BFGC ABCDEFGHI 1 BRIGHT A_FireCustomMissile("GreenFlareSpawn",0,0,0,0);
		//TNT1 AAA 0 A_FireCustomMissile("GreenFlareSpawn",0,0,0,0)
        BFGN A 0 A_Recoil(8);
        
        BFGN A 0 BRIGHT A_FireCustomMissile("Alerter", 0, 0, -1, 0);
		BFGN A 0 A_JumpIfInventory("DMgame", 1, 4);
		BFGN A 0 BRIGHT A_FireCustomMissile("BFGBall");
		BFGC I 2;
		//BFGN A 0;
		Goto RecoilFire;
		TNT1 AAA 0;
		BFGN A 0 BRIGHT A_FireCustomMissile("BFGBallDM");
		
	RecoilFire:
	    //BFGC I 2
		TNT1 A 0 A_SetPitch(Pitch-4);
		BFGC JKLMN 2 A_FireCustomMissile("GreenFlareSpawn",0,0,0,0);
		BFGN A 0 A_TakeInventory("BFGAmmo", 1);
		BFGN A 0 A_ZoomFactor(1.0);
		BFGN A 15 A_WeaponReady(WRF_NOFIRE);
        BFGN A 0 A_Refire;
		Goto Ready3;
		
		
	//Alpha Doom Attack, discontinued.	
	//AltFire:
	/*
		BFGN A 1;
		BFGN A 0 A_JumpIfInventory("AmmoCell", 50, 5);
		BFGN A 10;
		Goto Ready;
		TNT1 AAAAAA 0;
		BFGN A 0 A_TakeInventory("AmmoCell", 50);
        BFGN A 0 A_PlaySound("BFGCHARGE");
		BFGC ABCDABCDABCDABCD 1 BRIGHT;
		BFGC ABCDABCDABCDABCD 1 BRIGHT;
        BFGA A 2 BRIGHT A_FireCustomMissile("GreenFlareSpawn",0,0,0,0);
        BFGN A 0 A_PlaySound("BFGFIRE");
		TNT1 AAA 0 A_FireCustomMissile("GreenFlareSpawn",0,0,0,0);
        BFGN A 0 A_Recoil(8);
        //BFGN A 0 A_ZoomFactor(1.3)
        BFGN A 0 BRIGHT A_FireCustomMissile("Alerter", 0, 0, -1, 0);
		BFGN A 0 A_FireCustomMissile("ShakeYourAssDouble", 0, 0, 0, 0);
        BFGA BCBCBCBCBCB 2 BRIGHT A_FireCustomMissile("AlphaBFGBall", random(-6, 6), 0, 0, 0, 0, random(-2, 2));
		BFGA DE 2 BRIGHT;
        //BFGN A 0 A_ZoomFactor(1.0)
        BFGN A 1 BRIGHT;
		BFGN A 4;
        BFGN A 0  A_Refire;
		Goto Ready;
	*/

	/*
	Reload:
	    BFGN A 1;
		BFGN A 0 A_JumpIfInventory("BFGAmmo",1,1);
		Goto NoAmmo;
		BFGN A 0 A_JumpIfInventory("BFGBattery",2,"Ready3");
		BFGN BCDEF 1;
		BFGN A 0 A_JumpIfInventory("BFGBattery",1,2); // Don't spawn a casing if it's not empty.
		TNT1 A 0 A_FireCustomMissile("BFGBatteryCasingSpawn",0,0,-5,-30);
		BFGN GHI 2;
		BFGN JKLMMNNOOPPQQRR 1;
		TNT1 A 0 A_PlaySound("marine/superfist6",1);
		BFGN A 0 A_JumpIfInventory("BFGBattery",1,"NotEmpty");
		BFGN A 0 A_GiveInventory("BFGBattery",2);
		BFGN A 0 A_TakeInventory("BFGAmmo",2);
	FinishBFGReload:
		BFGN S 2;
		TNT1 A 0 A_PlaySound("BEP",2);
		BFGN TUVW 2;
		TNT1 A 0 A_PlaySound("BEP",2);
		BFGN B 1;
		Goto Ready;
	
	NotEmpty:;
	    BFGN A 0 A_GiveInventory("BFGBattery",1);
		BFGN A 0 A_TakeInventory("BFGAmmo",1);
		Goto FinishBFGReload;
	
	*/
	
	Flashkick:
	    BFGS DC 1;
	    BFGS B 14;
		BFGS CD 1;
		Stop;
		
	AirFlashkick:
	    BFGS DC 1;
	    BFGS B 16;
		BFGS CD 1;
		Stop;
	
	SlideFlashKick:
	    BFGS DC 1;
	    BFGS B 14;
		Stop;
	
	SlideFlashKickStop:
	    BFGS B 11;
		BFGS CD 1;
		Stop;
		

	
   
	
	Spawn:
		BFUG A -1;
		Stop;
	}
}