CLASS Rifle : BrutalWeapon
{
    bool Inspected,FiredGrenade;
	float Recoil;
 DEFAULT
 {
	Weapon.AmmoUse1 0;
	Weapon.AmmoGive1 0;
	Weapon.AmmoUse2 0;
	Weapon.AmmoGive2 0;
	YScale 0.6;
	XScale 0.8;
	Weapon.SelectionOrder 3900;
	Weapon.AmmoType1 "Clip2";
	Weapon.AmmoType2 "RifleAmmo";
	Weapon.SlotPriority 2;
	Obituary "%o was shot down by %k's assault rifle.";
    AttackSound "None";
    Inventory.PickupSound "CLIPIN";
	Inventory.Pickupmessage "$GOTRIFLE";
    +WEAPON.NOAUTOAIM;
    +WEAPON.NOALERT;
	+WEAPON.NOAUTOFIRE;
	+FORCEXYBILLBOARD;
	Tag "Assault Rifle";
    Scale 0.8;
}
  action void A_RifleRecoil ()
    {
	    // Set the recoil amount
        Invoker.Recoil = CVar.GetCVar('bd_riflerecoilscale', Player).Getfloat();
	}
	States
	{
	
		
	TacticalWarning:
		TNT1 A 4;
		Goto LetsGetStarted;
	WarmUp:
		RIFG A 0;
		RIFG A 0 A_TakeInventory("JustStartedGame", 1);
		RIFG A 0 A_JumpIfInventory("IsTacticalClass", 1, "TacticalWarning");
		
	Inspect:
	LetsGetStarted:	
		TNT1 A 0
		{
		 Invoker.Inspected = true;
		}
		PUNS ABCD 1 A_WeaponReady;
	    RIFG A 0 A_PlaySound("Knuckled");
		PUNS E 7 A_WeaponReady;
		PUNS FGFE 3 A_WeaponReady;
		PUNS DCB 1 A_WeaponReady;
		TNT1 A 5 A_WeaponReady;
		RIFG A 1 A_WeaponReady;
		Goto Ready3;
	
	/*
	CheckSprint:
		RIFG A 1 A_WeaponReady(WRF_NOFIRE)
		RIFG A 0 A_JumpIfInventory("IsStandingStill", 1, "Ready3")
		RIFG A 0 A_JumpIfInventory("IsTacticalClass", 1, "StartSprint")
		Goto Ready3
		
	CheckSprint2:
		RI2G A 1 A_WeaponReady(WRF_NOFIRE)
		RIFG A 0 A_JumpIfInventory("IsStandingStill", 1, "Ready3")
		RIFG A 0 A_JumpIfInventory("IsTacticalClass", 1, "StartSprint")
		Goto Ready2	
		
	StartSprint:
		RIFG A 1 A_WeaponReady(WRF_NOFIRE)
		RIFG A 0 A_Takeinventory("Zoomed",1)
		RIFG A 0 A_Takeinventory("ADSmode",1)
		RIFG A 0 A_ZoomFactor(1.0)
		RIFG A 0 A_JumpIfInventory("UsedStamina", 40, "StopSprintTired")
		
	Sprinting:	
		RIFG A 0
		RIFG A 0 A_JumpIfInventory("Accelerate", 1, 1)
		Goto Ready3
		RISP A 0 offset(-9,32) 
		RIFG A 0 offset(-9,32) A_JumpIfInventory("IsStandingStill", 1, "Ready3")
		RIFG A 0 offset(-9,32) A_JumpIfInventory("UsedStamina", 100, "StopSprintTired")
		PLAY A 0 offset(-9,32) ACS_ExecuteAlways(852, 0, 0, 0, 0)//Makes player faster.
		RIFG A 0 offset(-9,32) A_JumpIfInventory("PowerStrength", 1, 2)
		RIFG A 0 offset(-9,32) A_GiveInventory("UsedStamina", 5)
		RIFG A 0 offset(-9,32)
		RISP A 1 offset(-9,34) A_SetPitch(pitch -0.5)
		RISP A 1 offset(-6,36) A_SetPitch(pitch -0.5)
		RISP A 1 offset(-3,38) A_SetPitch(pitch -0.5)
		RISP A 1 offset(0,38) A_SetPitch(pitch -0.5)
		RISP A 1 offset(3,36) A_SetPitch(pitch -0.5)
		RISP A 1 offset(6,34) A_SetPitch(pitch -0.5)
		RISP A 1 offset(9,32) A_SetPitch(pitch -0.5)
		RIFG A 0 offset(9,32) A_WeaponReady(WRF_NOBOB)
		RIFG A 0 A_JumpIfInventory("Kicking",1,"DoKick")
        RIFG A 0 A_JumpIfInventory("Taunting",1,"Taunt")
        RIFG A 0 A_JumpIfInventory("Reloading",1,"Reload")
		RIFG A 0 offset(-9,32) A_GiveInventory("UsedStamina", 5)
		RIFG A 0 offset(9,33) A_SpawnItemEx("FootStep", 0, 0, 2, 0, 0, -4)
		RISP A 1 offset(9,34) A_SetPitch(pitch +0.5)
		RISP A 1 offset(6,36) A_SetPitch(pitch +0.5)
		RISP A 1 offset(3,38) A_SetPitch(pitch +0.5)
		RISP A 1 offset(0,38) A_SetPitch(pitch +0.5)
		RISP A 1 offset(-3,36) A_SetPitch(pitch +0.5)
		RISP A 1 offset(-6,34) A_SetPitch(pitch +0.5)
		RISP A 1 offset(-9,32) A_SetPitch(pitch +0.5)
		RIFG A 0 offset(-9,32) A_WeaponReady(WRF_NOBOB)
		RIFG A 0 offset(-9,32) A_JumpIfInventory("IsRunning", 1, "Sprinting")
		
		Goto StopSprint
	StopSprintTired:
		RIFG A 1
		PLAY A 0 ACS_ExecuteAlways(853, 0, 0, 0, 0)//Makes player slower.
		RIFG A 0 A_PlaySound("Tired", 2)
		RIFG A 0 A_TakeInventory("UsedStamina", 2)
		RIFG A 5 A_WeaponReady
		RIFG A 0 A_TakeInventory("UsedStamina", 2)
		RIFG A 5 A_WeaponReady
		RIFG A 0 A_TakeInventory("UsedStamina", 2)
		RIFG A 5 A_WeaponReady
		RIFG A 0 A_TakeInventory("UsedStamina", 2)
		RIFG A 5 A_WeaponReady
		RIFG A 0 A_TakeInventory("UsedStamina", 2)
		RIFG A 5 A_WeaponReady
		Goto Ready3
	StopSprint:
		RISP A 1
		RIFG A 0 A_JumpIfInventory("UsedStamina", 60, "StopSprintTired")
		PLAY A 0 ACS_ExecuteAlways(853, 0, 0, 0, 0)//Makes player slower.
		Goto Ready3
	*/	
	
	
	SelectAnimation:
        TNT1 AA 1 A_JumpIfInventory("GoFatality", 1, "Steady");
        TNT1 A 0
		{
		 if(Invoker.Inspected == true){return resolvestate(null);}
		 return resolvestate("Inspect");
		}
		RIFG A 0 A_PlaySound("CLIPIN");
		RIFG A 0 A_Takeinventory("BDWeaponACtion",1);
		TNT1 A 0 ZWL_QuickRaise();
		RIFA ABCD 1 Offset(0,32);
		RIFG A 0 A_Takeinventory("StartDualWield",1);
        TNT1 AAAA 0;
		Goto Ready;
	
	//IdleAnimation:
	    //RIFG A 0 A_Takeinventory("RifleIdle")
		//RIFR ABCDE 1 A_WeaponReady
		//RIFR E 10 A_WeaponReady
		//RIFR EDCBA 1 A_WeaponReady
		//Goto Ready3
	
	Ready:
	Ready3:
		TNT1 A 0 A_RifleRecoil();
		RIFG A 0 A_JumpIfInventory("Zoomed",1,"Ready2");
		TNT1 A 0 A_SetCrosshair(0);
		RIFG A 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("TossGrenade",1,"FireGrenade");
	    RIFG A 0 A_JumpIfInventory("Taunting",1,"Taunt");
        RIFG A 0 A_JumpIfInventory("Reloading",1,"Reload");
		//RIFG A 0 A_JumpIfInventory("Unloading",1,"Unload")
		RIFG A 0 A_JumpIfInventory("Salute1", 1, "Salute");
		RIFG A 0 A_JumpIfInventory("Salute2", 1, "Salute");
		//RIFG A 0 A_JumpIfInventory("Unloading",1,"Unload")
		//RIFG A 0 A_JumpIfInventory("IsRunning",1,"CheckSprint")
		RIFG A 0 A_JumpIfInventory("ExecuteDownedEnemy", 1, "DoExecution");
		RIFG A 0 A_JumpIfInventory("Kicking",1,"DoKick");
		RIFG A 0 A_JumpIfInventory("QuickMelee",1,"DoQuickMelee");
		//RIFG A 0 A_JumpIfInventory("StartDualWield",1,"DualWield")
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		Loop;
		
    Ready2:
	    TNT1 A 0 A_RifleRecoil();
		//RIFG A 0 A_Takeinventory("RifleIdle");
		RIFG A 0 A_JumpIfInventory("TossGrenade",1,"TossGrenade");
        RIFG A 0 A_JumpIfInventory("Taunting",1,"Taunt");
        RIFG A 0 A_JumpIfInventory("Reloading",1,"Reload");
		RIFG A 0 A_JumpIfInventory("Unloading",1,"Unload");
		RIFG A 0 A_JumpIfInventory("Salute1", 1, "Salute");
		RIFG A 0 A_JumpIfInventory("Salute2", 1, "Salute");
		RIFG A 0 A_JumpIfInventory("Kicking",1,"DoKick");
		RIFG A 0 A_JumpIfInventory("Unloading",1,"Unload");
		RIFG A 0 A_JumpIfInventory("StartDualWield",1,"DualWield");
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire2");
		RIFG A 0 A_JumpIfInventory("QuickMelee",1,"DoQuickMelee");
		//TNT1 A 0 A_SetCrosshair(41)
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("IsRunning",1,"CheckSprint2");
		RIFG A 0 A_TakeInventory("UsedStamina", 2);
		Loop;
	
		
	Deselect:
		TNT1 A 0
		{
		A_Giveinventory("ScreenTilt",1);
		A_Setroll(0, SPF_INTERPOLATE);
	    A_Takeinventory("ScreenTilt",1);
	    }
		RIFG A 0;
		//RIFG A 0 A_Takeinventory("RifleIdle");
		RIFG A 0 A_Takeinventory("Zoomed",1);
		RIFG A 0 A_Takeinventory("ADSmode",1);
		RIFG A 0 A_TakeInventory("TossGrenade", 1);
		RIFG A 0 A_TakeInventory("Kicking",1);
        RIFG A 0 A_TakeInventory("Taunting",1);
        RIFG A 0 A_TakeInventory("Reloading",1);
		RIFG A 0 A_TakeInventory("Unloading",1);
		RIFG A 0 A_TakeInventory("Salute1", 1);
		RIFG A 0 A_TakeInventory("Salute2", 1);
		RIFG A 0 A_Takeinventory("RifleSelected",1);
        RIFG A 0 A_ZoomFactor(1.0);
		RIFA DCBA 1;
		TNT1 A 0 ZWL_QuickLower();
		Wait;
		
	Select:
		TNT1 A 0 A_SetCrosshair(0);
		TNT1 A 0
		{
		A_Giveinventory("ScreenTilt",1);
		A_Setroll(0, SPF_INTERPOLATE);
	    A_Takeinventory("ScreenTilt",1);
	    }
		RIFG A 0;
		RIFG A 0 A_Takeinventory("StartDualWield",1);
		RIFG A 0 A_Giveinventory("GoSpecial",1);
		RIFG A 0 A_Takeinventory("FistsSelected",1);
		RIFG A 0 A_Takeinventory("SawSelected",1);
		RIFG A 0 A_Takeinventory("ShotgunSelected",1);
		RIFG A 0 A_Takeinventory("SSGSelected",1);
		RIFG A 0 A_Takeinventory("MinigunSelected",1);
		RIFG A 0 A_Takeinventory("PlasmaGunSelected",1);
		RIFG A 0 A_Takeinventory("RocketLauncherSelected",1);
		RIFG A 0 A_Takeinventory("GrenadeLauncherSelected",1);
		RIFG A 0 A_Takeinventory("BFGSelected",1);
		RIFG A 0 A_Takeinventory("BFG10kSelected",1);
		RIFG A 0 A_Takeinventory("RailGunSelected",1);
		RIFG A 0 A_Takeinventory("SubMachineGunSelected",1);
		RIFG A 0 A_Takeinventory("RevenantLauncherSelected",1);
		RIFG A 0 A_Takeinventory("LostSoulSelected",1);
		RIFG A 0 A_Takeinventory("FlameCannonSelected",1);
		RIFG A 0 A_Takeinventory("HasBarrel",1);
		RIFG A 0 A_TakeInventory("TossGrenade", 1);
		RIFG A 0 A_TakeInventory("IsRunning", 1);
		RIFG A 0 A_Giveinventory("RifleSelected",1);
		
		TNT1 A 0 ZWL_QuickRaise();
		Goto SelectAnimation;
	
    Fire:
	    RIFG A 0 A_JumpIfInventory("RifleAmmo",1,1);
        Goto NoAmmo;
		RIFG A 0 A_JumpIfInventory("Zoomed",1,"Fire2");
		RIFF A 1 BRIGHT 
		{
		 A_AlertMonsters();
		 A_FireCustomMissile("DistantFireSoundRifle", random(-1,1), 0, 0, -12, 0, random(-1,1));
		 A_StartSound("weapons/rifle",1,CHANF_OVERLAP,1);
		 ZWL_FireHitscan(0, 40, pellets:1, spread:0, damagetype:"", pufftype:"HitPuff",tracertype:"PistolTracer",Offset:(0,0,-5));
		 A_SpawnItemEx("PlayerMuzzle1",30,5,30);
		 A_FireCustomMissile("RifleCaseSpawn",0,0,0,-15);
		 A_SetPitch(pitch-Invoker.Recoil, SPF_INTERPOLATE);
		 A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		 A_Takeinventory("RifleAmmo",1);
		}
		RIFF B 1 A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		RIFF C 1 A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		RI2F B 0 A_ReFire;
		RIFG A 1 
		{
		A_weaponready(WRF_ALLOWRELOAD);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		Goto Ready3;
	
     Fire2:
		RIFG A 0;
		RIFG A 0 A_SpawnItemEx("PlayerMuzzle1",30,0,45);
		RIFG A 0 A_PlaySound("weapons/rifle", 1);
	
        RI2F A 1 BRIGHT 
		{
		ZWL_FireHitscan(0, 40, pellets:1, spread:0, damagetype:"", pufftype:"HitPuff",tracertype:"PistolTracer",Offset:(0,0,-5));
		 A_SetPitch(pitch-Invoker.Recoil, SPF_INTERPOLATE);
		}
		RIFG A 0 A_Takeinventory("RifleAmmo",1);
		RIFG A 0 A_ZoomFactor(2.0);
		RIFG A 0 A_FireCustomMissile("RifleCaseSpawn",0,0,0,-15);
        RI2F C 1; 
		RI2F D 1; 
		RI2F E 1; 
		RIFG A 0;
		RI2G B 1;
		RIFG A 0;
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RIFG A 0 A_JumpIfInventory("FiredSecondary",1,"HoldAim");//If still pressing alt fire, it means its holding aim
        RI2F B 0 A_ReFire;
		RIFG A 0 A_JumpIfInventory("ZoomHold", 1, "NoAim");
        RI2G A 0;
		Goto Ready2;
	
	FireGrenade:
	    RIFG A 0 A_JumpIfInventory("GrenadeAmmo",1,4);
        TNT1 A 0 A_Print("NoGrenades");
		TNT1 A 0 A_PlaySound("weapons/empty", 4);
		Goto Ready3;
		TNT1 A 0;
		TNT1 A 0 A_Takeinventory("TossGrenade",1);
		TNT1 A 0
		{
		 if(Invoker.FiredGrenade == true){return resolvestate("ReloadGrenade");}
		 return resolvestate(null);
		}
		TNT1 A 0
		{
		 Invoker.FiredGrenade = true;
		}
		RIFF A 1 BRIGHT 
		{
		 A_AlertMonsters();
		 A_FireCustomMissile("DistantFireSoundRifle", random(-1,1), 0, 0, -12, 0, random(-1,1));
		 A_StartSound("assaultrifle/grenade",1,CHANF_OVERLAP,1);
		 ZWL_FireProjectile("ARifleGrenade", 0, -1, offset:(0,0,-5), flags:ZPF_AddPlayerVel);
		 A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		 A_SpawnItemEx("PlayerMuzzle1",30,5,30);
		 A_SetPitch(pitch-0.5, SPF_INTERPOLATE);
		 A_Takeinventory("GrenadeAmmo",1);
		}
		RIFF C 1 A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
		RIFG A 1 A_WeaponReady;
		Goto ReloadGrenade;
		
    AltFire:
       TNT1 A 0 A_SetCrosshair(41);
	   //RIFG A 0 A_Takeinventory("RifleIdle");
		RIFG A 0;
		RIFG A 0 A_Giveinventory("GoSpecial",1);
		RIFG A 0 A_JumpIfInventory("Zoomed",1,"NoAim");
		RIFG A 0 A_Giveinventory("Zoomed",1);
        RIFG A 0 A_ZoomFactor(2.0);
		RIFG A 0 A_Giveinventory("ADSmode",1);
        //RIFZ ABC 1
		RIFF C 1;
		RI2G A 1;
		//RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD)
		
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		
		
		RIFG A 0 A_JumpIfInventory("FiredSecondary",1,"HoldAim");
        Goto Ready2;
		
	   HoldAim:	
		RIFG A 0 A_GiveInventory("ZoomHold",1);
	    RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"Fire");
		RI2G B 1 A_WeaponReady(WRF_ALLOWRELOAD);
		RIFG A 0 A_JumpIfInventory("FiredSecondary",1,"HoldAim");
		
       NoAim:
		RIFG A 0;
		RIFG A 0 A_Takeinventory("Zoomed",1);
		RIFG A 0 A_Takeinventory("ZoomHold",1);
        RIFG A 0 A_ZoomFactor(1.0);
		RIFG A 0 A_Takeinventory("ADSmode",1);
		RIFZ BA 1;
        Goto Ready3;
			
		
	NoAmmo:
		RIFG A 0;
		RIFG A 0 A_ZoomFactor(1.0);
		RIFG A 0 A_Takeinventory("Zoomed",1);
		RIFG A 0 A_Takeinventory("ADSmode",1);
		RIFG A 0 A_JumpIfInventory("TurboReload",1,"TurboReload");
		TNT1 A 0 A_PlaySound("weapons/empty", 4);
		NoAmmo2:
		RIFG A 0 A_JumpIfInventory("TossGrenade",1,"TossGrenade");
	    RIFG A 0 A_JumpIfInventory("Taunting",1,"Taunt");
		RIFG A 0 A_JumpIfInventory("Salute1", 1, "Salute");
		RIFG A 0 A_JumpIfInventory("Salute2", 1, "Salute");
		RIFG A 0 A_JumpIfInventory("IsRunning",1,"CheckSprint");
		RIFG A 0 A_JumpIfInventory("ExecuteDownedEnemy", 1, "DoExecution");
		RIFG A 0 A_JumpIfInventory("Kicking",1,"DoKick");
		RIFG A 5 A_WeaponReady(WRF_ALLOWRELOAD | WRF_NOFIRE);
		RIFG A 0 A_JumpIfInventory("Reloading",1,"Reload");
		RIFG A 0 A_JumpIfInventory("TurboReload",1,"TurboReload");
		TNT1 A 0 A_JumpIfInventory("NoAutoReload", 1, "NoAmmo2");
		RIFG A 0 A_JumpIfInventory("Clip2",1,"Reload");
		RIFG A 0 A_JumpIfInventory("FiredPrimary",1,"NoAmmo2");
		Goto Ready3;
	
    Reload:
		RIFG A 1 A_WeaponReady;
		RIFG A 0 A_JumpIfInventory("RifleAmmo",31,"Ready3");
		RIFG A 0 A_JumpIfInventory("TurboReload",1,"TurboReload");
		RIFG A 0 A_ZoomFactor(1.0);
		RIFG A 0 A_Takeinventory("Reloading",1);
		RIFG A 0 A_Takeinventory("ADSmode",1);
		RIFG A 0 A_Takeinventory("Zoomed",1);
		RIFG A 0 A_JumpIfInventory("TurboReload",1,"TurboReload");
        RIFG A 0 A_JumpIfInventory("Clip2",1,3);
		Goto Ready3;
        TNT1 AAA 0;
		RIFG A 0 A_Takeinventory("Zoomed",1);
		RIFG A 0 A_Takeinventory("Reloading",1);
		RIFG A 0 A_JumpIfInventory("TurboReload",1,"TurboReload");
        RIFG A 0 A_JumpIfInventory("RifleAmmo",1,"TacticalReload");
		RIFR ABCDE 1 A_WeaponReady(WRF_NOFIRE);
		RIFG A 0 A_PlaySound("CLIPOUT", 1);
		TNT1 A 0 A_FireCustomMissile("EmptyClipSpawn",-5,0,8,-4);
		RIFR FGHIJKLMN 1 A_WeaponReady(WRF_NOFIRE);
		RIFG A 0 A_PlaySound("CLIPIN", 1);
		RIFR PQRS 1 A_WeaponReady(WRF_NOFIRE);
		//RIFG A 0 A_PlaySound("CLIPIN", 1);
		TNT1 A 0 A_PlaySound("BLTBCK", 1);
		RIFR TUVW 1 A_WeaponReady(WRF_NOFIRE);
		TNT1 A 0 A_PlaySound("BLTFRW", 6);
		RIFR XYZ 1 A_WeaponReady(WRF_NOFIRE);
		RI2R ABCDEFG 1 A_WeaponReady(WRF_NOFIRE);
		Goto InsertBullets;
	
	FinishReload:
	    RIFR ECBA 1 A_WeaponReady(WRF_NOFIRE);
		Goto InsertBullets2;
	
	/*
	ReloadUnloaded:
	    //RIFG A 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH)
		RI2R RQPO 1 A_WeaponReady(WRF_NOFIRE)
		RIFR K 10 A_WeaponReady(WRF_NOFIRE)
		RIFR LNPRSTTTUV 1 A_WeaponReady(WRF_NOFIRE)
		RIFG A 0 A_PlaySound("CLIPIN", 6)
		RIFR WXYZ 1 A_WeaponReady(WRF_NOFIRE)
        RI2R ABCDEF 1 A_WeaponReady(WRF_NOFIRE)
		RI2R GHIJKL 1 A_WeaponReady(WRF_NOFIRE)
		RI2R MN 1 A_WeaponReady(WRF_NOFIRE)
		RIFR A 1 A_WeaponReady(WRF_NOFIRE)
		Goto InsertBullets2
	*/	
	
	TacticalReload:
		//RIFG A 0 A_PlaySound("CLIPOUT", 1);
		RI3R ABCDEFGH 1 A_WeaponReady(WRF_NOFIRE);
		RIFG A 0 A_PlaySound("CLIPOUT", 1);
		RI3R IJKL 1 A_WeaponReady(WRF_NOFIRE);
		RI3R M 5;
		RI3R NOPQ 1 A_WeaponReady(WRF_NOFIRE);
		RIFG A 0 A_PlaySound("CLIPIN", 1);
		RI3R RSFEDCBA 1 A_WeaponReady(WRF_NOFIRE);
		Goto InsertBullets2;
	
	ReloadGrenade:
	    TNT1 A 0
		{
		 Invoker.FiredGrenade = false;
		}
		RIFR ABCDE 1 A_WeaponReady(WRF_NOFIRE); 
		TNT1 A 0 A_StartSound("assaultrifle/grenadeopen",1,CHANF_OVERLAP,1);
		RIGR AAAAABBCCDDEEE 1 A_WeaponReady(WRF_NOFIRE);
		TNT1 A 0 A_StartSound("assaultrifle/grenadeload",1,CHANF_OVERLAP,1);
		RIGR FFF 1 A_WeaponReady(WRF_NOFIRE);
		TNT1 A 0 A_StartSound("assaultrifle/grenadeclose",1,CHANF_OVERLAP,1);
		RIGR GGGG 1 A_WeaponReady(WRF_NOFIRE);
		RIFR EDCBA 1 A_WeaponReady(WRF_NOFIRE);
		Goto Ready3;
			
	TurboReload:
		RIFG A 0 A_Takeinventory("HasUnloaded",1);
		RIFG A 0 A_JumpIfInventory("Clip2",1,3);
		Goto Ready3;
		RIFS ABC 0;
        Goto InsertBullets;
		
	InsertBullets:
		TNT1 AAAA 0;
		RIFG A 0 A_JumpIfInventory("RifleAmmo",30,"Ready3");
		RIFG A 0 A_JumpIfInventory("Clip2",1,3);
		Goto Ready3;
        TNT1 AAAAAA 0;
		RIFG A 0 A_Giveinventory("RifleAmmo",1);
		RIFG A 0 A_Giveinventory("DoubleRifleAmmo",1);
		RIFG A 0 A_Takeinventory("Clip2",1);
		Goto InsertBullets;
		
		//TNT1 AAAAAAAAAA 0;
		//RIFG A 0 A_Takeinventory("Reloading",1);
		
		//RIFG A 0 A_Refire;
        //Goto FinishReloading;
		//TNT1 AAAA 0;
		//RIFG A 0 A_Takeinventory("Reloading",1);
		
		//RIFG A 0 A_Refire;
        //Goto FinishReloading;
		
	InsertBullets2:
		TNT1 AAAA 0;
		RIFG A 0 A_JumpIfInventory("RifleAmmo",31,"Ready3");
		RIFG A 0 A_JumpIfInventory("Clip2",1,3);
		Goto Ready3;
        TNT1 AAAAAA 0;
		RIFG A 0 A_Giveinventory("RifleAmmo",1);
		RIFG A 0 A_Giveinventory("DoubleRifleAmmo",1);
		RIFG A 0 A_Takeinventory("Clip2",1);
		Goto InsertBullets2;
			
	Unload:
		//RIFG A 1 A_WeaponReady
		RIFG A 0 A_ZoomFactor(1.0);
		RIFG A 0 A_Takeinventory("Unloading",1);
		RIFG A 0 A_Takeinventory("ADSmode",1);
		RIFG A 0 A_Takeinventory("Zoomed",1);
        RIFG A 0 A_JumpIfInventory("RifleAmmo",1,3);
        Goto NoAmmo;
        TNT1 AAA 0;
		RIFG A 0 A_Takeinventory("Zoomed",1);
		RIFR ABCDE 1 A_WeaponReady(WRF_NOFIRE);
		//RIFG A 0 A_JumpIfInventory("RifleAmmo",1,"TacticalReload")
		RIFG A 0 A_PlaySound("CLIPOUT", 6);
		RIFR FGHIJ 1 A_WeaponReady(WRF_NOFIRE);
		RIFR K 1 A_WeaponReady(WRF_NOFIRE);
		RI2R OPQR 1 A_WeaponReady(WRF_NOFIRE);
		RIFR BA 1 A_WeaponReady(WRF_NOFIRE);
		RIFG A 0 A_GiveInventory("HasUnloaded", 1);
		RIFG A 0 A_Takeinventory("Unloading",1);
		
	RemoveBullets:
		TNT1 AAAA 0;
		RIFG A 0 A_JumpIfInventory("RifleAmmo",2,3);
		Goto Ready3;
        TNT1 AAAAAA 0;
		RIFG A 0 A_Takeinventory("RifleAmmo",1);
		RIFG A 0 A_Takeinventory("DoubleRifleAmmo",1);
		RIFG A 0 A_Giveinventory("Clip2",1);
		Goto RemoveBullets;
	
	//FInishUnload:
		//RIFS HGF 1
		//RIFR A 1
		//RIFG A 0 A_PlaySound("DryFire")
		//RIFG A 0 A_GiveInventory("HasUnloaded", 1)
		//RIFG A 0 A_Takeinventory("Unloading",1)
		//Goto Ready3
		
		
		
 	Spawn:
		RIFL A -1;
		Stop;
		
	DualWield:
		RIFG A 1;
		RIFG A 0 A_Takeinventory("StartDualWield",1);
		Goto Ready;
		
	Execution2:
		RIFG A 0;
		RIFG A 0 A_ZoomFactor(1.1);
		RIBB A 1 A_Stop;
        RIBB B 1 A_PlaySound("skeleton/swing");
		RIBB C 1 A_FireCustomMissile("ExecutionAttackMelee", 0, 0, 0, 0);
		RIBB D 6 A_Stop;
		RIBB CBA 2 A_Stop;
		
		RIBB A 1 A_Stop;
        RIBB B 1 A_PlaySound("skeleton/swing");
		RIBB C 1 A_FireCustomMissile("ExecutionAttackMelee", 0, 0, 0, 0);
		RIBB D 6 A_Stop;
		RIBB CBA 2 A_Stop;
		
		
		RIBB A 1 A_Stop;
        RIBB B 1 A_PlaySound("skeleton/swing");
		RIBB C 1 A_FireCustomMissile("ExecutionAttackKick", 0, 0, 0, 0);
		RIBB D 6 A_Stop;
		RIBB CBA 2 A_Stop;
		
		TNT1 A 5;
		Goto FinishExecution;
	
	//FlashMelee:
	Flashkick:
	    RIFA DCB 1;
	    RIFA A 13;
		RIFA BCD 1;
		Stop;
	/*
	FlashMelee:
	    RIFK ABC 1;
	    RIFK D 1;
		RIFK CBD 1;
		Stop;
	*/	
		
	AirFlashkick:
	    RIFA DCB 1;
	    RIFA A 14;
		RIFA BCD 1;
		Stop;
	
	SlideFlashKick:
	    RIFA DCB 1;
	    RIFA A 13;
		Stop;
	
	SlideFlashKickStop:
	    RIFS A 10;
		RIFS BCD 1;
		Stop;
	
	}
}