
CLASS SSG : BrutalWeapon
{
 bool Inspected;
 float recoil;
 DEFAULT
 {
    //Game Doom
	//SpawnID 33
    Weapon.Kickback 50;
	Weapon.SelectionOrder 400;
	Weapon.AmmoGive1 4;
	Weapon.AmmoGive2 0;
	Weapon.AmmoType1 "AmmoShell";
	Weapon.AmmoType2 "SSGAmmo";
	Weapon.AmmoUse1 0;
	Weapon.AmmoUse2 0;
    +WEAPON.NOAUTOAIM;
	+WEAPON.NOAUTOFIRE;
	+FORCEXYBILLBOARD;
	Inventory.PickupMessage "$GOTSHOTGUN2";
	Obituary "$OB_MPSSHOTGUN";
    Inventory.PickupSound "CLIPINSS";
	Scale 0.9;
	Tag "Super Shotgun";
}
 action void A_SSGRecoil ()
    {
	    // Set the recoil amount
        Invoker.Recoil = CVar.GetCVar('bd_SSGrecoilscale', Player).Getfloat();
	}
	States
	{
	
	InspectSSG:
	TNT1 A 0
		{
		 Invoker.Inspected = true;
		}
	SHTZ AB 1 A_WeaponReady();
		SHTZ C 1
		{
		  A_WeaponReady();
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); 
	   }
	//ReloadB:
		SHTZ D 1
		{
		  A_Giveinventory("ScreenTilt",1);
		  A_WeaponReady();
		  A_Setroll(roll+0.8, SPF_INTERPOLATE);
		  A_PlaySound("weapons/ssg/open",2);
	   }
	   SHTZ EF 1
	   {
		 A_WeaponReady();
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); // +0.7
	   }
	   SHTZ G 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.6, SPF_INTERPOLATE); 
	   }
	   SHTZ G 4
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.2, SPF_INTERPOLATE); 
	   }
	   SHTZ HIJK 1 A_WeaponReady();
	   SSGR ABCDEFGHI 1 A_WeaponReady();
	   SHTZ A 0 A_playsound("weapons/ssg/in",3);
	   SHTZ L 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); 
	   }
	   SHTZ M 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll+0.4, SPF_INTERPOLATE); // +0.3
	   }
	   SHTZ N 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); 
	   }
	   SHTZ O 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll+0.4, SPF_INTERPOLATE); 
	   }
	   SHTZ P 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); // +0.1
	   }
	   SHTZ Q 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); //-0.1
		  A_playsound("weapons/ssg/close",3);
	   }
	   SHTZ RST 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-1.2, SPF_INTERPOLATE); //-1.9
	   }
	   SHTZ U 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-1.0, SPF_INTERPOLATE); //-2.4
	   }
	   SHTZ V 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.6, SPF_INTERPOLATE); //-2.7
	   }
	   SHTZ WXY 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.2, SPF_INTERPOLATE); //-3.0
	   }
	   SHTZ Z 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll+1.0, SPF_INTERPOLATE); //-2.5
		  A_playsound("weapons/ssg/close",3);
	   }
	   SHTX AB 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll+2.5, SPF_INTERPOLATE); //0
	   }
	   SHTX C 1
	   {
		  A_WeaponReady();
		  A_Setroll(roll-0.8, SPF_INTERPOLATE); //0
	   }
	   SHTZ A 1
	   {
		  A_takeinventory("ScreenTilt",1);
		  A_WeaponReady();
		  A_Setroll(0, SPF_INTERPOLATE); //0
	   }
		SHTZ A 0 A_TakeInventory("SSGAlt",1);
        Goto Ready;
    SelectAnimation:    
	Ready:
	Ready3:
	    TNT1 A 0 
		{
		A_SSGRecoil();
		}
	    //TNT1 A 0 A_SetCrosshair(46);
		SHTZ A 1 A_WeaponReady(WRF_ALLOWRELOAD);
        SHTZ A 0 A_JumpIfInventory("Kicking",1,"DoKick");
        SHTZ A 0 A_JumpIfInventory("Taunting",1,"Taunt");
		SHTZ A 0 A_JumpIfInventory("Salute1", 1, "Salute");
		SHTZ A 0 A_JumpIfInventory("Salute2", 1, "Salute");
		SHTZ A 0 A_JumpIfInventory("Reloading",1,"Reload");
		SHTZ A 0 A_JumpIfInventory("Unloading",1,"Unload");
		SHTZ A 0 A_JumpIfInventory("TossGrenade",1,"TossGrenade")	;
		//SHTZ A 0 A_JumpIfInventory("IsRunning",1,"CheckSprint");
		SHTZ A 0 A_JumpIfInventory("QuickMelee",1,"DoQuickMelee");
		Loop;
		
	/*	
	CheckSprint:
		SHTZ A 1 A_WeaponReady(WRF_NOFIRE)
		SHTZ A 0 A_JumpIfInventory("IsStandingStill", 1, "Ready3")
		SHTZ A 0 A_JumpIfInventory("IsTacticalClass", 1, "StartSprint")
		Goto Ready
		
	StartSprint:
		SHTZ A 1 A_WeaponReady(WRF_NOFIRE)
		SHTZ A 0 A_Takeinventory("Zoomed",1)
		SHTZ A 0 A_Takeinventory("ADSmode",1)
		SHTZ A 0 A_ZoomFactor(1.0)
		SHTZ A 0 A_JumpIfInventory("UsedStamina", 40, "StopSprintTired")
		
	Sprinting:	
		SSRU A 0 offset(-9,32) 
		SHTZ A 0 offset(-9,32) A_JumpIfInventory("IsStandingStill", 1, "Ready3")
		SHTZ A 0 offset(-9,32) A_JumpIfInventory("UsedStamina", 100, "StopSprintTired")
		PLAY A 0 offset(-9,32) ACS_ExecuteAlways(852, 0, 0, 0, 0)//Makes player faster.
		SHTZ A 0 offset(-9,32) A_JumpIfInventory("PowerStrength", 1, 2)
		SHTZ A 0 offset(-9,32) A_GiveInventory("UsedStamina", 6)
		SHTZ A 0 offset(-9,32)
		SSRU A 1 offset(-9,34) A_SetPitch(pitch -0.5)
		SSRU A 1 offset(-6,36) A_SetPitch(pitch -0.5)
		SSRU A 1 offset(-3,38) A_SetPitch(pitch -0.5)
		SSRU A 1 offset(0,38) A_SetPitch(pitch -0.5)
		SSRU A 1 offset(3,36) A_SetPitch(pitch -0.5)
		SSRU A 1 offset(6,34) A_SetPitch(pitch -0.5)
		SSRU A 1 offset(9,32) A_SetPitch(pitch -0.5)
		SHTZ A 0 offset(9,32) A_WeaponReady()(WRF_NOBOB)
		SHTZ A 0 A_JumpIfInventory("Kicking",1,"DoKick")
        SHTZ A 0 A_JumpIfInventory("Taunting",1,"Taunt")
        SHTZ A 0 A_JumpIfInventory("Reloading",1,"Reload")
		SHTZ A 0 offset(-9,32) A_GiveInventory("UsedStamina", 6)
		SHTZ A 0 offset(9,33) A_SpawnItemEx("FootStep", 0, 0, 2, 0, 0, -4)
		SSRU A 1 offset(9,34) A_SetPitch(pitch +0.5)
		SSRU A 1 offset(6,36) A_SetPitch(pitch +0.5)
		SSRU A 1 offset(3,38) A_SetPitch(pitch +0.5)
		SSRU A 1 offset(0,38) A_SetPitch(pitch +0.5)
		SSRU A 1 offset(-3,36) A_SetPitch(pitch +0.5)
		SSRU A 1 offset(-6,34) A_SetPitch(pitch +0.5)
		SSRU A 1 offset(-9,32) A_SetPitch(pitch +0.5)
		SHTZ A 0 offset(-9,32) A_WeaponReady()(WRF_NOBOB)
		SHTZ A 0 offset(-9,32) A_JumpIfInventory("IsRunning", 1, "Sprinting")
		
		Goto StopSprint
	StopSprintTired:
		SHTZ A 1
		PLAY A 0 ACS_ExecuteAlways(853, 0, 0, 0, 0)//Makes player slower.
		SHTZ A 0 A_PlaySound("Tired", 2)
		SHTZ A 0 A_TakeInventory("UsedStamina", 2)
		SHTZ A 5 A_WeaponReady()
		SHTZ A 0 A_TakeInventory("UsedStamina", 2)
		SHTZ A 5 A_WeaponReady()
		SHTZ A 0 A_TakeInventory("UsedStamina", 2)
		SHTZ A 5 A_WeaponReady()
		SHTZ A 0 A_TakeInventory("UsedStamina", 2)
		SHTZ A 5 A_WeaponReady()
		SHTZ A 0 A_TakeInventory("UsedStamina", 2)
		SHTZ A 5 A_WeaponReady()
		Goto Ready
	StopSprint:
		SSRU A 1
		SHTZ A 0 A_JumpIfInventory("UsedStamina", 60, "StopSprintTired")
		PLAY A 0 ACS_ExecuteAlways(853, 0, 0, 0, 0)//Makes player slower.
		Goto Ready
	*/	
		
	PuristGun:
		TNT1 A 1;
		SHTZ A 0 A_GiveInventory("ClassicSSG", 1);
		SHTZ A 0 A_TakeInventory("SSG", 1);
		TNT1 A 10;
		Goto Ready;
		
	Deselect:
	    TNT1 A 0
		{
		A_Giveinventory("ScreenTilt",1);
		A_Setroll(0, SPF_INTERPOLATE);
	    A_Takeinventory("ScreenTilt",1);
	    }
		SHTZ A 0 offset(0,32);
		SHTZ A 0 A_Takeinventory("Zoomed",1);
        SHTZ A 0 A_ZoomFactor(1.0);
		SHTZ A 0 A_TakeInventory("TossGrenade", 1);
		SHT5 DCBA 1;
		TNT1 A 0 ZWL_QuickLower();
		Wait;
	Select:
		TNT1 A 0
		{
		A_Giveinventory("ScreenTilt",1);
		A_Setroll(0, SPF_INTERPOLATE);
	    A_Takeinventory("ScreenTilt",1);
	    }
		TNT1 A 0
		{
		 if(Invoker.Inspected == true){return resolvestate(null);}
		 return resolvestate("InspectSSG");
		}
		SHTZ A 0 offset(0,32);
		SHTZ A 0 A_Giveinventory("GoSpecial",1);
		SHTZ A 0 A_Takeinventory("FistsSelected",1);
		SHTZ A 0 A_Takeinventory("SawSelected",1);
		RIFG A 0 A_Takeinventory("RifleSelected",1);
		SHTZ A 0 A_Takeinventory("ShotgunSelected",1);
		SHTZ A 0 A_Giveinventory("SSGSelected",1);
		SHTZ A 0 A_Takeinventory("MinigunSelected",1);
		SHTZ A 0 A_Takeinventory("PlasmaGunSelected",1);
		SHTZ A 0 A_Takeinventory("RocketLauncherSelected",1);
		SHTZ A 0 A_Takeinventory("GrenadeLauncherSelected",1);
		SHTZ A 0 A_Takeinventory("BFGSelected",1);
		SHTZ A 0 A_Takeinventory("BFG10kSelected",1);
		SHTZ A 0 A_Takeinventory("RailGunSelected",1);
		SHTZ A 0 A_Takeinventory("SubMachineGunSelected",1);
		SHTZ A 0 A_Takeinventory("RevenantLauncherSelected",1);
		SHTZ A 0 A_Takeinventory("LostSoulSelected",1);
		SHTZ A 0 A_Takeinventory("FlameCannonSelected",1);
		SHTZ A 0 A_Takeinventory("HasBarrel",1);
		SHTZ A 0 A_TakeInventory("TossGrenade", 1);
		SHTZ A 0 A_JumpIfInventory("SSGAmmo", 1, 1);
		Goto RaiseReloading;
		TNT1 A 0 ZWL_QuickRaise();
		SHT5 ABCD 1;
		SHTZ A 0 A_PlaySound("weapons/sshotc");
		Goto Ready;
		
	RaiseReloading:
		SHTZ A 0 A_JumpIfInventory("AmmoShell", 2,1);//Check if has any ammo left to reload
		Goto RaiseNoAmmo;
		TNT1 A 0;
		Goto Reload;
		
	RaiseNoAmmo:	
		TNT1 A 0 ZWL_QuickRaise();
		SHTZ YZ 1;
		SHTX ABBC 1;
		SHTZ A 0 A_PlaySound("weapons/sshotc");
		Goto Ready;

	NoAmmo:
		SHTZ A 0;
		SHTZ A 0 A_ZoomFactor(1.0);
		SHTZ A 0 A_Takeinventory("Zoomed",1);
		SHTZ A 0 A_Takeinventory("ADSmode",1);
		TNT1 A 0 A_PlaySound("weapons/empty", 4);
		Goto Ready3;
	NoAmmo2:
		SHTZ A 0 A_JumpIfInventory("TossGrenade",1,"TossGrenade");
	    SHTZ A 0 A_JumpIfInventory("Taunting",1,"Taunt");
		SHTZ A 0 A_JumpIfInventory("Salute1", 1, "Salute");
		SHTZ A 0 A_JumpIfInventory("Salute2", 1, "Salute");
		SHTZ A 0 A_JumpIfInventory("IsRunning",1,"CheckSprint");
		SHTZ A 0 A_JumpIfInventory("ExecuteDownedEnemy", 1, "DoExecution");
		SHTZ A 0 A_JumpIfInventory("Kicking",1,"DoKick");
		SHTZ A 5 A_WeaponReady(WRF_ALLOWRELOAD | WRF_NOFIRE);
		SHTZ A 0 A_JumpIfInventory("Reloading",1,"Reload");
		TNT1 A 0 A_JumpIfInventory("NoAutoReload", 1, "Ready3");
		SHTZ A 0 A_JumpIfInventory("AmmoShell",1,"Reload");
		SHTZ A 0 A_JumpIfInventory("FiredPrimary",1,"NoAmmo2");
		Goto Ready3;
		
	 Fire:
		SHTZ A 0 A_TakeInventory("Reloading",1);
		SHTZ A 0 A_JumpIfInventory("SSGAlt",1,"AltFire");
		SHTZ A 0 A_JumpIfInventory("SSGAmmo", 2, 1);
		Goto NoAmmo;
		
		SHTZ A 0 A_TakeInventory("SSGAmmo", 2);
		SHTZ A 0 A_JumpIfInventory("PowerStrength", 1, 2);
		SHTZ A 0 A_Recoil(5);
		SHTZ A 0;
		SHTZ A 0 A_FireCustomMissile("DistantFireSoundSSG", random(-1,1), 0, 0, -12, 0, random(-1,1));
		TNT1 AAAAAAAAAAAAA 0 BRIGHT A_FireCustomMissile("ShotgunParticles2", random(-19,19), 0, -1, 0, 0, random(-9,9));
		SHOF A 1 BRIGHT
		{
		A_StartSound("SGFIRE",1,CHANF_OVERLAP,1);
		A_StartSound("SGFIRE",1,CHANF_OVERLAP,1);
		A_SpawnItemEx("PlayerMuzzle2",30,5,27);
		A_firebullets (0,0,1,40,"shotpuff",FBF_NORANDOM,300);
		ZWL_FireHitscan(5, 40, pellets:10, spread:5, damagetype:"", pufftype:"ShotgunPuff",tracertype:"PistolTracer",Offset:(0,0,-5));
		A_SetPitch(pitch-Invoker.Recoil, SPF_INTERPOLATE);
		A_SetPitch(pitch-Invoker.Recoil, SPF_INTERPOLATE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		
		SHTZ A 0 A_ZoomFactor(1.00);
        SHTZ A 0 A_TakeInventory("SSGAlt",1);
        SHTZ A 0 A_TakeInventory("Reloading",1);
		SHT3 H 1 //A_WeaponReady(WRF_NOFIRE);
		{
		A_WeaponReady(WRF_NOFIRE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		SHOF D 1
		{
		A_WeaponReady(WRF_NOFIRE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		SHOF EFFFFFGHIJ 1
		{
		A_WeaponReady(WRF_NOFIRE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		Goto NoAmmo2;

     AltFire:
		SHTZ A 0 A_TakeInventory("Reloading",1);
		SHTZ A 0 A_JumpIfInventory("SSGAmmo",1,3);
        Goto NoAmmo;
        TNT1 AAAAA 0;
		SHTZ A 0 A_JumpIfInventory("SSGAlt",1,"AltFire2");


		SHTZ A 0 A_TakeInventory("SSGAmmo",1);
		SHTZ A 0 A_GiveInventory("SSGAlt",1);
	    TNT1 AAAAA 0 BRIGHT A_FireCustomMissile("ShotgunParticles2", random(-12,12), 0, -1, 0, 0, random(-9,9));
		SHT3 A 1 BRIGHT
		{
		A_AlertMonsters();
		//A_PlaySound("SSHFIRE2", 1);
		A_StartSound("SGFIRE",1,CHANF_OVERLAP,1);
		A_SpawnItemEx("PlayerMuzzle1",30,5,30);
		A_FireCustomMissile("DistantFireSoundShotgun", random(-1,1), 0, 0, -12, 0, random(-1,1));
		ZWL_FireHitscan(2.5, 40, pellets:5, spread:2.5, damagetype:"", pufftype:"ShotgunPuff",tracertype:"PistolTracer",Offset:(0,0,-5));
		A_SetPitch(pitch-Invoker.Recoil, SPF_INTERPOLATE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		SHT3 CDEEE 1
		{
		A_WeaponReady(WRF_NOFIRE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		SHT3 C 1
		{
		A_WeaponReady(WRF_NOFIRE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
        Goto Ready;

	AltFire2:
		SHTZ A 0 A_TakeInventory("Reloading",1);
		SHTZ A 0 A_TakeInventory("SSGAmmo", 1);
        SHTZ A 0 A_ALertMonsters;
		SHTZ AA 0 A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
		TNT1 AAAAA 0 BRIGHT A_FireCustomMissile("ShotgunParticles2", random(-12,12), 0, -1, 0, 0, random(-9,9));
        //TNT1 A 0 A_PlaySound("SGFIRE", 1);
		SHTZ A 0 A_SpawnItemEx("PlayerMuzzle1",30,5,30);
		SHTZ A 0 A_FireCustomMissile("DistantFireSoundShotgun", random(-1,1), 0, 0, -12, 0, random(-1,1));
		SHT3 B 1 BRIGHT
		{
		A_AlertMonsters();
		//A_PlaySound("SSHFIRE2", 1);
		//A_StartSound("SSHFIRE2",1,CHANF_DEFAULT,1);
		A_StartSound("SGFIRE",1,CHANF_OVERLAP,1);
		A_SpawnItemEx("PlayerMuzzle1",30,5,30);
		A_FireCustomMissile("DistantFireSoundShotgun", random(-1,1), 0, 0, -12, 0, random(-1,1));
		ZWL_FireHitscan(2.5, 40, pellets:5, spread:2.5, damagetype:"", pufftype:"ShotgunPuff",tracertype:"PistolTracer",Offset:(0,0,-5));
		A_SetPitch(pitch-Invoker.Recoil, SPF_INTERPOLATE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		SHT3 FGHHH 1
		{
		A_WeaponReady(WRF_NOFIRE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		SHT3 C 1
		{
		A_WeaponReady(WRF_NOFIRE);
		A_FireCustomMissile("GunFireSmoke", 0, 0, 0, 1, 0, 0);
		}
		
		SHTZ A 0 A_TakeInventory("SSGAlt", 1);
		Goto NoAmmo2;
	
	Reload:	
		SHTZ A 0;
		
		SHTZ A 0 A_TakeInventory("Reloading",1);
		
		//SHTZ A 0 A_JumpIfInventory("SSGAlt",2,"AltReloadBothBarrels")
		SHTZ A 0 A_JumpIfInventory("SSGAlt", 1, "Reload2");//Check if still has a shell on left barrel
		
		SHTZ A 0 A_JumpIfInventory("SSGAmmo", 2, "Ready");
		
		SHTZ A 0 A_JumpIfInventory("AmmoShell", 2, 1);//Check if has any ammo left to reload
		Goto Ready;
		
		
		//Reload 2 barrels
	
		//SHTZ DEFGHHHHIJ 1
		//SHTZ ABCDEF 1 A_WeaponReady(WRF_NOFIRE)
		SHTZ AB 1 A_WeaponReady(WRF_NOFIRE);
		SHTZ C 1
		{
		  A_Giveinventory("ScreenTilt",1);
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); 
	   }
	//ReloadB:
		//SHTZ A 0 A_JumpIfInventory("HasUnloaded", 1, 2)
		TNT1 AA 0 A_FireCustomMissile("SSGCaseSpawner",0,0,-10, -20);
		SHTZ D 1
		{
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.8, SPF_INTERPOLATE);
		  A_PlaySound("weapons/ssg/open",2);
	   }
	   SHTZ EF 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); // +0.7
	   }
	   SHTZ G 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.6, SPF_INTERPOLATE);
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
	   }
	   SHTZ G 4
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.2, SPF_INTERPOLATE); 
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
	   }
	   SHTZ HIJK 1 A_WeaponReady(WRF_NOFIRE);
	   SSGR I 1 A_WeaponReady(WRF_NOFIRE);
	   SHTZ A 0 A_playsound("weapons/ssg/in",3);
	   SHTZ L 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); 
	   }
	   SHTZ M 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.4, SPF_INTERPOLATE); // +0.3
	   }
	   SHTZ N 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); 
	   }
	   SHTZ O 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.4, SPF_INTERPOLATE); 
	   }
	   SHTZ P 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); // +0.1
	   }
	   SHTZ Q 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); //-0.1
		  //A_playsound("weapons/ssg/close",3);
		  A_TakeInventory("AmmoShell", 2);
		  A_GiveInventory("SSGAmmo", 2);
	   }
	   SHTZ R 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.2, SPF_INTERPOLATE); 
	   }
	   SHTZ S 1
	   {
	      A_playsound("weapons/ssg/close",3);
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.2, SPF_INTERPOLATE);
	   }
	   SHTZ T 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.2, SPF_INTERPOLATE); //-1.9
	   }
	   SHTZ U 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.0, SPF_INTERPOLATE); //-2.4
	   }
	   SHTZ V 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.6, SPF_INTERPOLATE); //-2.7
	   }
	   SHTZ WXY 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.2, SPF_INTERPOLATE); //-3.0
	   }
	   SHTZ Z 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+1.0, SPF_INTERPOLATE); //-2.5
		  //A_playsound("weapons/ssg/close",3);
	   }
	   SHTX AB 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+2.5, SPF_INTERPOLATE); //0
	   }
	   SHTX C 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.8, SPF_INTERPOLATE); //0
	   }
	   SHTZ A 1
	   {
		  A_takeinventory("ScreenTilt",1);
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(0, SPF_INTERPOLATE); //0
	   }
		SHTZ A 0 A_TakeInventory("SSGAlt",1);
        Goto Ready;
        
	Reload2:
		SHTZ A 0 A_TakeInventory("Reloading",1);
		SHTZ A 0 A_JumpIfInventory("AmmoShell",1,1);
		Goto NoAmmo;
		SHTZ A 0 A_TakeInventory("SSGAlt",1);
		SHTZ B 1 A_WeaponReady(WRF_NOFIRE);
		SHT7 A 1
		{
		  A_Giveinventory("ScreenTilt",1);
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); 
	   }
		TNT1 A 0 A_FireCustomMissile("SSGCaseSpawner",0,0,-10, -20);
		SHT7 B 1
		{
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.8, SPF_INTERPOLATE);
		  A_PlaySound("weapons/ssg/open",2);
	   }
	   SHT7 CD 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); // +0.7
	   }
	   SHT7 E 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.6, SPF_INTERPOLATE);
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
	   }
	   SHT7 E 4
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.2, SPF_INTERPOLATE);
		  A_FireCustomMissile("GunFireSmoke", 0, 0, -2, 0, 0, 0);
	   }
	   SHT7 FGHIJ 1 A_WeaponReady(WRF_NOFIRE);
	   SSGR I 1 A_WeaponReady(WRF_NOFIRE);
	   SHTZ A 0 A_playsound("weapons/ssg/in",3);
	   SHTZ L 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.2, SPF_INTERPOLATE); 
	   }
	   SHTZ M 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.4, SPF_INTERPOLATE); // +0.3
	   }
	   SHTZ N 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); 
	   }
	   SHTZ O 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+0.4, SPF_INTERPOLATE); 
	   }
	   SHTZ P 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); // +0.1
	   }
	   SHTZ Q 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.4, SPF_INTERPOLATE); //-0.1
		  //A_playsound("weapons/ssg/close",3);
		  A_TakeInventory("AmmoShell", 1);
		  A_GiveInventory("SSGAmmo", 1);
	   }
	   SHTZ R 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.2, SPF_INTERPOLATE); 
	   }
	   SHTZ S 1
	   {
	      A_playsound("weapons/ssg/close",3);
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.2, SPF_INTERPOLATE);
	   }
	   SHTZ T 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.2, SPF_INTERPOLATE); //-1.9
	   }
	   SHTZ U 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-1.0, SPF_INTERPOLATE); //-2.4
	   }
	   SHTZ V 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.6, SPF_INTERPOLATE); //-2.7
	   }
	   SHTZ WXY 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.2, SPF_INTERPOLATE); //-3.0
	   }
	   SHTZ Z 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+1.0, SPF_INTERPOLATE); //-2.5
		  //A_playsound("weapons/ssg/close",3);
	   }
	   SHTX AB 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll+2.5, SPF_INTERPOLATE); //0
	   }
	   SHTX C 1
	   {
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(roll-0.8, SPF_INTERPOLATE); //0
	   }
	   SHTZ A 1
	   {
		  A_takeinventory("ScreenTilt",1);
		  A_WeaponReady(WRF_NOFIRE);
		  A_Setroll(0, SPF_INTERPOLATE); //0
	   }
		SHTZ A 0 A_TakeInventory("SSGAlt",1);
        Goto Ready;
			
	Spawn:
		SGN2 A -1;
		Stop;
	
    
		
	
	Unload:
		SHTZ A 1 A_WeaponReady();
		SHTZ A 0 A_ZoomFactor(1.0);
		SHTZ A 0 A_Takeinventory("Unloading",1);
		SHTZ A 0 A_Takeinventory("ADSmode",1);
		SHTZ A 0 A_Takeinventory("Zoomed",1);
        SHTZ A 0 A_JumpIfInventory("SSGAmmo",1,3);
        Goto Ready;
        TNT1 AAA 0;
		SHTZ A 0 A_Takeinventory("Zoomed",1);
		SHTZ A 0 A_GiveInventory ("Pumping", 1);
		SHTZ A 0 A_Takeinventory("Unloading",1);
		
	RemoveBullets:
		TNT1 AAAA 0;
		SHTZ A 0 A_JumpIfInventory("SSGAmmo",1,3);
		Goto FinishUnload;
        TNT1 AAAAAA 0;
		SHTZ A 0 A_Takeinventory("SSGAmmo",1);
		SHTZ A 0 A_Giveinventory("AmmoShell",1);
		Goto RemoveBullets;
	
	FInishUnload:
		SHTZ BC 1;
		SHTZ A 0 A_PlaySound("weapons/ssg/open",2);
		SHTU A 1;
		SHTZ EFG 1;
		SHTU BCDE 1;
		SHTZ PQR 1;
		SHTZ A 0 A_GiveInventory ("Pumping", 1);
		SHTZ STUVXYZ 1 A_WeaponReady(WRF_NOFIRE);
		SHTZ A 0 A_playsound("weapons/ssg/close",3);
		SHTX ABC 1;
		SHTZ A 0 A_TakeInventory("SSGAlt",1);
        Goto Ready;
	
	Flashkick:
	    SHT5 DCB 1;
	    SHT5 A 13;
		SHT5 BCD 1;
		Stop;
		
	AirFlashkick:
	    SHT5 DCB 1;
	    SHT5 A 14;
		SHT5 BCD 1;
		Stop;
	
	SlideFlashKick:
	    SHT5 DCB 1;
	    SHT5 A 13;
		Stop;
	
	SlideFlashKickStop:
	    SHT5 A 10;
		SHT5 BCD 1;
		Stop;
	
	}
}
